//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GranTurismoFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class OwnedCar
    {
        public int OwnedCarId { get; set; }
        public int CarId { get; set; }
        public int PrimaryDriverId { get; set; }
        public string ImageName { get; set; }
    }
}
