//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GranTurismoFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTrial
    {
        public int TimeTrialId { get; set; }
        public int TrackId { get; set; }
        public int TuneId { get; set; }
        public System.TimeSpan Time { get; set; }
        public int DriverId { get; set; }
        public int SessionId { get; set; }
        public int OwnedCarId { get; set; }
    }
}
