//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GranTurismoFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tune
    {
        public int TuneId { get; set; }
        public int CarId { get; set; }
        public double PerformancePoints { get; set; }
        public int TiresFrontId { get; set; }
        public int TiresRearId { get; set; }
        public string SheetName { get; set; }
        public double HorsePower { get; set; }
        public double Weight { get; set; }
        public string Notes { get; set; }
    }
}
